create table public.budgets (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  user_id bigint not null,
  month integer not null,
  year integer not null,
  amount numeric not null,
  constraint budgets_pkey primary key (id),
  constraint unique_budget_per_user_date unique (user_id, month, year),
  constraint budgets_month_check check (
    (
      (month >= 1)
      and (month <= 12)
    )
  )
) TABLESPACE pg_default;

create table public.daily_registers (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  user_id bigint not null,
  opened_at timestamp with time zone not null default now(),
  closed_at timestamp with time zone null,
  initial_amount numeric not null default 0,
  final_amount numeric null,
  status text not null default 'open'::text,
  constraint daily_registers_pkey primary key (id),
  constraint daily_registers_status_check check (
    (
      status = any (array['open'::text, 'closed'::text])
    )
  )
) TABLESPACE pg_default;

create table public.expenses (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  description text not null,
  amount numeric not null,
  date date not null,
  user_id bigint not null,
  daily_register_id bigint null,
  payment_method text not null default 'efectivo'::text,
  constraint expenses_pkey primary key (id),
  constraint expenses_daily_register_id_fkey foreign KEY (daily_register_id) references daily_registers (id),
  constraint expenses_payment_method_check check (
    (
      payment_method = any (
        array[
          'efectivo'::text,
          'tarjeta'::text,
          'transferencia'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create table public.usuarios2 (
  id bigint generated by default as identity not null,
  email text not null,
  password text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint usuarios2_pkey primary key (id),
  constraint usuarios2_email_key unique (email)
) TABLESPACE pg_default;